version: "3"
services:
  one:
    build: .
    ports: ["5001:5000"]
    environment:
      - NODE_NAME=one
      - NODE_URLS=one;two;three
  two:
    build: .
    ports: ["5002:5000"]
    environment:
      - NODE_NAME=two
      - NODE_URLS=one;two;three
  three:
    build: .
    ports: ["5003:5000"]
    environment:
      - NODE_NAME=three
      - NODE_URLS=one;two;three
